Updated profiles to fit BBMRI guidelines
samply/bbmri-fhir-ig pull request #13
Opened 2019-07-25 14:40 UTC by noemide

- Added ValueSet, CodeSystem & Extension for 
1. Data categories
2. collection types 
3. quality standards.

- Added Code "research" for use as contact type
- Updated Biobank to use ADMIN and RESEARCH in the respective contact slices & included quality extension
- Collection: Added extensions, added identifier for BBMRI ID, changed contact slincing to be like Biobank
- Updated documentation

2019-07-26 11:04 UTC, alexanderkiel requested changes

2019-07-26 11:04 UTC, alexanderkiel commented on extension/DataCategory.StructureDefinition.json
> +  "name": "DataCategory",
Can you provide a description here? I don't known what a data category is.

2019-07-26 11:04 UTC, alexanderkiel commented on terminology/valueset/ValueSetBbmriCollectionTypes.json
> +  "name": "ValueSetBbmriCollectionTypes",
Isn't it redundant to repeat `ValueSet` where?

2019-07-26 11:04 UTC, alexanderkiel commented on extension/collectionTypes.StructureDefinition.json
> +  "url": "https://fhir.bbmri.de/StructureDefinition/collectionType",
title case

2019-07-26 11:04 UTC, alexanderkiel commented on extension/quality-standards.StructureDefinition.json
> +  "name": "quality-standards",
naming convention

2019-07-26 11:04 UTC, alexanderkiel commented on extension/quality-standards.StructureDefinition.json
> +  "status": "draft",
description

2019-07-26 11:04 UTC, alexanderkiel commented on profile/GbaCollection.StructureDefinition.json
> +  "name": "Collection",
description

2019-07-26 11:04 UTC, alexanderkiel commented on terminology/codesystem/CodeSystemBbmriCollectionTypes.json
> +  "url": "https://fhir.bbmri.de/CodeSystem/CodeSystemBbmriCollectionTypes",
redundant `CodeSystem`

2019-07-26 12:45 UTC, noemide commented on terminology/valueset/ValueSetBbmriCollectionTypes.json
> +  "name": "ValueSetBbmriCollectionTypes",
Terminology resources are now named according to the not-outdated part of the de-basis IG (https://simplifier.net/guide/basisprofil-de-r4/NomenklaturderRessourcen)  "ValueSets, die alle Konzepte eines CodeSystems vollständig enthalten, tragen den selben Namen wie das CodeSystem"

2019-07-26 13:41 UTC, alexanderkiel requested changes

2019-07-26 13:41 UTC, alexanderkiel commented on profile/BbmriCauseOfDeath.StructureDefinition.json
>                "http://hl7.org/fhir/StructureDefinition/Patient",
should we use our own patient here?

2019-07-26 14:07 UTC, alexanderkiel approved these changes

2019-07-28 17:53 UTC, alexanderkiel commented
We forgot `Condition.onsetDateTime`. So please add it.

2019-07-29 10:08 UTC, alexanderkiel commented
Do you think we need `Condition.abatement[x]`? I would keep it simple and use only one date for now.

2019-07-29 12:50 UTC, noemide commented
> 
> 
> Do you think we need `Condition.abatement[x]`? I would keep it simple and use only one date for now.

In my opinion, if we support onset, we should also at least have the option to use abatement. (Both are not mandatory) We also have recordedDate, for cases in which only a system timestamp is available. (Also not mandatory for cases in which no date information is present, but i will recommend using at least recordedDate or onsetDate in the textual IG)

2019-07-29 15:21 UTC, alexanderkiel commented
Ok recordedDate is useful if one has no onsetDateTime information available. In queries we can see us using onsetDateTime with a fallback to recordedDate. But I don't see us using abatementDateTime. If we ask "get all specimen with a collectedDateTime up to x amount of days after a condition happened (onset) or was known (recorded), what should abatementDateTime help us here? Do you have an example?

2019-07-29 15:29 UTC, noemide commented
E.g. Sample from a patient with Condition A while they also had Condition B. Concrete example: Patient who had chronic pneumonia and developed lung cancer (in contrast to having and recovering from pneumonia some time before the cancer). Im not sure if the UI supports such queries yet, but it may be useful for future applications - and since it is optional, biobanks can choose not to provide the data until it becomes relevant.

2019-07-29 15:51 UTC, alexanderkiel commented
Ok we make all three dates optional and explain in the IG that we plan to use onset with recorded as fallback in first date-based queries and abatement maybe later. ok?

2019-07-29 15:52 UTC, noemide commented
Sounds good :)

2019-07-29 15:54 UTC, alexanderkiel commented
Do you plan to rename the profiles in this feature branch or in the next one?

2019-07-29 15:58 UTC, noemide commented
I currently plan to use the next one where i already started setting mustSupport flags. (And also because we're still waiting on feedback and this may take a while.) But we can also leave this PR open until it is decided?

2019-07-29 18:16 UTC, alexanderkiel commented
I think both issues, removing Bbmri and using Patient/Specimen is decided. I would put that changes in this PR. Maybe also the ICD-10 validation if possible. Else I would merge this PR and move on.

2019-07-31 10:52 UTC, merged